config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root "tweets#index"
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get '/users/sign_out', to: redirect('/')


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private 

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all.order("created_at DESC")
    @tweet = Tweet.new
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy!

    respond_to do |format|
      format.html { redirect_to tweets_path, status: :see_other, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def van(email, size: 64, alt: nil, class_name: nil)
    image_path = "van.jpg"
    alt_text = alt || "Image for #{email}"
    
    image_tag(image_path, alt: alt_text, class: class_name, style: "width: #{size}px; height: #{size}px;")
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Twitty" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if flash[:notice] %>
    <div class="notification is-primary global-notification">
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>
  <nav class="navbar is-black">
    <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-5">Xx</h1>
      <% end %>
      <div class="navbar-burger burger" data-target="navbarExample">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <div id="navbarExample" class="navbar-menu">
      <div class="navbar-end">
        <div class="buttons">
          <%= link_to 'New Tweet', root_path, class: "button is-black is-inverted" %>
            <% if user_signed_in? %>
            <%= link_to current_user.name, edit_user_registration_path, class: "button is-black" %>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "button is-black" %>
          <% else %>
            <%= link_to 'Sign Up', new_user_registration_path, class: "button is-black" %>
            <%= link_to 'Sign In', new_user_session_path, class: "button is-black" %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>

  <%= yield %>
</body>

</html>

app/views/tweets/_feed.html.erb
<div class="column is-half">
    <% if user_signed_in? %>
    <article class="media box">
        <figure class="media-left">
            <p class="image is-64x64">
              <%= van(current_user.email, size: 64, alt: current_user.name) %>
            </p>
        </figure>
        <div class="media-content">
            <%= render 'tweets/form' %>
        </div>
    </article>
    <% end %>


<% @tweets.each do | tweet | %>
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <%= van(tweet.user.email, size: 64, alt: tweet.user.name) %>
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <strong><%= tweet.user.name %></strong><br />
                    <small><%= tweet.user.username %></small><br />
                    <p><%= tweet.tweet %></p>
                </div>
                <% if user_signed_in? %>
                <nav class="level">
                    <div class="level-left is-mobile">
                        <%= link_to tweet, class: "level-item" do %>
                            <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                        <% end %>
                        <%= link_to edit_tweet_path(tweet), class: "level-item" do %>
                            <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                        <% end %>
                        <%= link_to tweet, method: :delete, data: { confirm: "Are you sure you want to delete this tweet?" } do %>
                            <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                        <% end %>
                    </div>
                </nav>
                <% end %>
            </div>
        </article>
    </div>
<% end %>
</div>

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :tweet, label: "Tweet at your own risk", input_html: { class: "textarea"}, wrapper: false, label_html: {class: "label"}, placeholder: "What is happening?!" %>
  </div>
</div>
<%= f.button :submit, "Post", class: "button is-black" %>
<% end %>

app/views/tweets/_profile.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Profile</p>
    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <%= van(current_user.email, size: 64, alt: current_user.name) %>
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong><%= current_user.name %></strong><br />
                        <small><%= current_user.username %></small>
                    </p>
                </div>
            </div>
        </article>
    </div>
    <div class="panel-block">
        <div class="level is-mobile">
            <div class="level-item has-centered-text">
                <div>
                    <p class="heading">Tweets</p>
                    <p class="title is-6"><%= current_user.tweets.count %></p>
                </div>
            </div>
            <div class="level-item has-centered-text">
                <div>
                    <p class="heading">Following</p>
                    <p class="title is-6">11</p>
                </div>
            </div>
            <div class="level-item has-centered-text">
                <div>
                    <p class="heading">Followers</p>
                    <p class="title is-6">512k</p>
                </div>
            </div>
        </div>
    </div>
  </nav>
</div>

app/views/tweets/_trends.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Trends</p>
    <a class="panel-block">
        Trend 1
    </a>
    <a class="panel-block">
        Trend 2
    </a>
    <a class="panel-block">
        Trend 3
    </a>
    <a class="panel-block">
        Trend 4
    </a>
    <a class="panel-block">
        Trend 5
    </a>
    <a class="panel-block">
        Trend 6
    </a>
  </nav>
</div>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <strong>Tweet:</strong>
    <%= tweet.tweet %>
  </p>

</div>

app/views/tweets/_who-to-follow.html.erb
<div class="column">
    <nav class="panel">
        <p class="panel-heading">Who to Follow</p>
    </nav>
    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/assets/images/placeholders/64x64.png"/>
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>Shawty bente</strong>
                        <br/>
                        <small>@shawties</small>
                    </p>
                </div>
            </div>
        </article>
    </div>
    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/assets/images/placeholders/64x64.png"/>
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>Shawty bente</strong>
                        <br/>
                        <small>@shawties</small>
                    </p>
                </div>
            </div>
        </article>
    </div>
    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/assets/images/placeholders/64x64.png"/>
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>Shawty bente</strong>
                        <br/>
                        <small>@shawties</small>
                    </p>
                </div>
            </div>
        </article>
    </div>
    </nav>
</div>

                    

app/views/tweets/edit.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <div class="box">
          <h1 class="title">Editing Tweet</h1>
          <%= render 'form', tweet: @tweet %>
        </div>
      </div>
    </div>
  </div>

  <nav class="navbar is-fixed-bottom">
    <div classs="navbar-menu">
        <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to "Cancel", tweets_path, class: "button is-dark" %>
            </p>
          </div>
        </div>
      </div>

app/views/tweets/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
    <% if user_signed_in? %>
      <%= render 'profile' %>
    <% else %>
      <%= render 'trends' %>
    <% end %>

      <%= render 'feed' %>
      <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/tweets/new.html.erb
<% content_for :title, "New tweet" %>

<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>